/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solutions;


import solutions.reverselinkedlist.ListNode;
import solutions.reverselinkedlist.ReverseLinkedList;

public class App {

    public static void main(String[] args) {
        ReverseLinkedList reverseLinkedList = new ReverseLinkedList();

        ListNode one = new ListNode(1,
                new ListNode(2,
                        new ListNode(3,
                                new ListNode(4,
                                        new ListNode(5, null)))));

        ListNode result = reverseLinkedList.reverseList(one);
        ListNode.printList(result);
    }
}
